# Generated by Django 5.1.7 on 2025-03-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donation_app', '0002_bloodrequest_delete_donor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BecomeDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('blood_type', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('preferred_donation_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
